New table and change on function.
YanAmorelli/gym_consistency pull request #1
Opened 2022-12-27 19:14 UTC by caioabreu11

Added a presence table that's related with user_info table, and the function that login a user now just returns a bool value.

2022-12-27 19:25 UTC, YanAmorelli requested changes
@caioabreu11 o que você acha da sugestão?

2022-12-27 19:25 UTC, YanAmorelli commented on database/1-tables.sql
> +	 status      BOOL,
Não ficaria melhor ao invés de status colocarmos algo como: wentGym? Ou algo do gênero, um nome mais descritivo?

2022-12-27 19:27 UTC, caioabreu11 commented on database/1-tables.sql
> +	 status      BOOL,
Realmente seria melhor deixar algo mais especifico, vou fazer a mudança.

2022-12-27 19:32 UTC, YanAmorelli requested changes

2022-12-27 19:32 UTC, YanAmorelli commented on database/1-tables.sql
> +CREATE TABLE user_presence (
Ao invés de presence, usa attendance por favor. É mais correto

2023-01-03 17:29 UTC, YanAmorelli approved these changes

2023-01-03 17:29 UTC, YanAmorelli commented on database/1-tables.sql
> +	 dt_presence DATE ,
dt_attendance

2023-01-03 17:29 UTC, YanAmorelli commented on database/1-tables.sql
> +	 presence_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
attendance_id

2023-01-03 17:29 UTC, YanAmorelli commented on database/1-tables.sql
> +CREATE UNIQUE INDEX dt_presence_user_id ON user_presence
dt_attendance_user_id on user_attendance

2023-01-03 17:29 UTC, YanAmorelli commented on database/1-tables.sql
> +(dt_presence, user_id);
dt_attendance

2023-01-03 17:29 UTC, merged